### PR TITLE
feature: support non standard parse

### PR DESCRIPTION
**Pull request by lizuncong**
Supports parsing of non-standard formulas, that is, formulas without spaces before and after $ or $$. For example：

```javascript
var testTxt = `
afdaf$x=x^2$4$x=x^2$

$$
x = x^2
$$
`
const options = {
    throwOnError: false,
    nonStandard: true
};
marked.use(markedKatex(options));
marked.parse(testTxt)
```

can be rendered normally into：

image

or：

image

### CODE REVIEW

**Comment by UziTech** [comment]
Can you add tests and add the new option the the readme.

**Comment by lizuncong** [comment]
@UziTech I don't know how to write test

**Comment by UziTech** [comment]
You can create a test in https://github.com/UziTech/marked-katex-extension/blob/main/spec/index.test.js

**Comment by lizuncong** [comment]
@UziTech ok, I try try.

**Comment by lizuncong** [comment]
@UziTech It's ok. you see see, my friend.

**Comment by lizuncong** [comment]
@UziTech I have added unit tests

**Comment by lizuncong** [comment]
@UziTech Hello bro, could you make a merge?

**Pull request merged**
