### PR TITLE
fix: nonStandard option does not exist

### PR DESCRIPTION
**Pull request by YangFong**

### CODE REVIEW

**Comment by YangFong** [comment]
Fix this issue:

image

**Comment by UziTech** [comment]
Nice catch! Can you add a type test in https://github.com/UziTech/marked-katex-extension/blob/main/spec/index.test-d.ts?

**Comment by YangFong** [comment]
@UziTech I've further tweaked index.d.ts to make it more flexible, and type testing has been updated accordingly.

**Review by UziTech — APPROVED** [review]
Thanks! 💯

**Pull request merged**
